<?php

/**
 * ERP Modules Configuration
 * 
 * Định nghĩa các module ERP và capabilities của từng module
 * Mỗi module có thể có quyền truy cập module (module.access) 
 * và các quyền chi tiết (module.entity.action)
 */

return [
    // Party Module: Quản lý Person/Organization và PartyRole
    'party' => [
        'name' => 'Party Management',
        'description' => 'Quản lý Party (Person/Organization) và PartyRole (Manager, Agent, Tenant)',
        'capabilities' => [
            'party.access' => 'Truy cập module Party',
            'party.person.view' => 'Xem Person',
            'party.person.create' => 'Tạo Person',
            'party.person.update' => 'Cập nhật Person',
            'party.person.delete' => 'Xóa Person',
            'party.organization.view' => 'Xem Organization',
            'party.organization.create' => 'Tạo Organization',
            'party.organization.update' => 'Cập nhật Organization',
            'party.organization.delete' => 'Xóa Organization',
            'party.role.view' => 'Xem PartyRole',
            'party.role.assign' => 'Gán PartyRole',
            'party.role.revoke' => 'Thu hồi PartyRole',
            'party.tenant.view' => 'Xem Tenant',
            'party.tenant.create' => 'Tạo Tenant',
            'party.tenant.update' => 'Cập nhật Tenant',
            'party.tenant.delete' => 'Xóa Tenant',
            'party.user_banking.view_others' => 'Xem thông tin ngân hàng của người khác',
            'party.user_banking.update_others' => 'Cập nhật thông tin ngân hàng của người khác',
            'party.salary_contract.view' => 'Xem Salary Contract',
            'party.salary_contract.create' => 'Tạo Salary Contract',
            'party.salary_contract.update' => 'Cập nhật Salary Contract',
            'party.salary_contract.delete' => 'Xóa Salary Contract',
            'party.salary_contract.terminate' => 'Chấm dứt Salary Contract',
            'party.user.view' => 'Xem User',
            'party.user.view_all' => 'Xem tất cả Users',
            'party.user.view_own' => 'Chỉ xem Users có role người thuê',
            'party.user.create' => 'Tạo User',
            'party.user.update' => 'Cập nhật User',
            'party.user.delete' => 'Xóa User',
        ],
    ],

    // CRM Module: Lead, Contact, Appointment, PipelineStage
    'crm' => [
        'name' => 'CRM Management',
        'description' => 'Quản lý Lead, Contact, Appointment, PipelineStage',
        'capabilities' => [
            'crm.access' => 'Truy cập module CRM',
            'crm.lead.view' => 'Xem Lead',
            'crm.lead.view_all' => 'Xem tất cả Leads',
            'crm.lead.view_own' => 'Chỉ xem Leads của mình',
            'crm.lead.create' => 'Tạo Lead',
            'crm.lead.update' => 'Cập nhật Lead',
            'crm.lead.delete' => 'Xóa Lead',
            'crm.contact.view' => 'Xem Contact',
            'crm.contact.create' => 'Tạo Contact',
            'crm.contact.update' => 'Cập nhật Contact',
            'crm.contact.delete' => 'Xóa Contact',
            'crm.appointment.view' => 'Xem Appointment',
            'crm.appointment.view_all' => 'Xem tất cả Appointments',
            'crm.appointment.view_own' => 'Chỉ xem Appointments của mình',
            'crm.appointment.create' => 'Tạo Appointment',
            'crm.appointment.update' => 'Cập nhật Appointment',
            'crm.appointment.delete' => 'Xóa Appointment',
            'crm.pipeline.view' => 'Xem Pipeline',
            'crm.pipeline.manage' => 'Quản lý PipelineStage',
            'crm.review.view' => 'Xem Review',
            'crm.review.update' => 'Cập nhật Review',
            'crm.review.delete' => 'Xóa Review',
            'crm.review.reply' => 'Phản hồi Review',
        ],
    ],

    // Asset/Inventory Module: Property (Building, Unit, Amenity, UnitStatus, Meter)
    'asset' => [
        'name' => 'Asset & Inventory Management',
        'description' => 'Quản lý Property (Building, Unit, Amenity, UnitStatus, Meter)',
        'capabilities' => [
            'asset.access' => 'Truy cập module Asset',
            'asset.property.view' => 'Xem Property',
            'asset.property.view_all' => 'Xem tất cả Properties',
            'asset.property.view_own' => 'Chỉ xem Properties được gán',
            'asset.property.create' => 'Tạo Property',
            'asset.property.update' => 'Cập nhật Property',
            'asset.property.delete' => 'Xóa Property',
            'asset.unit.view' => 'Xem Unit',
            'asset.unit.view_all' => 'Xem tất cả Units',
            'asset.unit.view_own' => 'Chỉ xem Units của Properties được gán',
            'asset.unit.create' => 'Tạo Unit',
            'asset.unit.update' => 'Cập nhật Unit',
            'asset.unit.delete' => 'Xóa Unit',
            'asset.amenity.view' => 'Xem Amenity',
            'asset.amenity.manage' => 'Quản lý Amenity',
            'asset.status.manage' => 'Quản lý UnitStatus',
            'asset.meter.view' => 'Xem Meter',
            'asset.meter.create' => 'Tạo Meter',
            'asset.meter.update' => 'Cập nhật Meter',
            'asset.meter.delete' => 'Xóa Meter',
            'asset.meter_reading.view' => 'Xem Meter Reading',
            'asset.meter_reading.create' => 'Tạo Meter Reading',
            'asset.meter_reading.update' => 'Cập nhật Meter Reading',
            'asset.meter_reading.delete' => 'Xóa Meter Reading',
            'asset.property_type.view' => 'Xem Property Type',
            'asset.property_type.create' => 'Tạo Property Type',
            'asset.property_type.update' => 'Cập nhật Property Type',
            'asset.property_type.delete' => 'Xóa Property Type',
        ],
    ],

    // Contract Module: Lease, LeaseResident, Addendum, DepositRefund
    'contract' => [
        'name' => 'Contract Management',
        'description' => 'Quản lý Lease, LeaseResident, Addendum, DepositRefund',
        'capabilities' => [
            'contract.access' => 'Truy cập module Contract',
            'contract.lease.view' => 'Xem Lease',
            'contract.lease.view_all' => 'Xem tất cả Leases',
            'contract.lease.view_own' => 'Chỉ xem Leases của mình',
            'contract.lease.create' => 'Tạo Lease',
            'contract.lease.update' => 'Cập nhật Lease',
            'contract.lease.delete' => 'Xóa Lease',
            'contract.lease.terminate' => 'Chấm dứt Lease',
            'contract.lease.renew' => 'Gia hạn Lease',
            'contract.master_lease.view' => 'Xem Master Lease',
            'contract.master_lease.create' => 'Tạo Master Lease',
            'contract.master_lease.update' => 'Cập nhật Master Lease',
            'contract.master_lease.delete' => 'Xóa Master Lease',
            'contract.resident.view' => 'Xem LeaseResident',
            'contract.resident.manage' => 'Quản lý LeaseResident',
            'contract.addendum.view' => 'Xem Addendum',
            'contract.addendum.manage' => 'Quản lý Addendum',
            'contract.deposit_refund.view' => 'Xem Deposit Refund',
            'contract.deposit_refund.view_all' => 'Xem tất cả Deposit Refunds',
            'contract.deposit_refund.view_own' => 'Chỉ xem Deposit Refunds của mình',
            'contract.deposit_refund.create' => 'Tạo Deposit Refund',
            'contract.deposit_refund.update' => 'Cập nhật Deposit Refund',
            'contract.deposit_refund.delete' => 'Xóa Deposit Refund',
            'contract.deposit_refund.approve' => 'Duyệt Deposit Refund',
            'contract.deposit_refund.pay' => 'Thanh toán Deposit Refund',
            'contract.booking_deposit.view' => 'Xem Booking Deposit',
            'contract.booking_deposit.view_all' => 'Xem tất cả Booking Deposits',
            'contract.booking_deposit.view_own' => 'Chỉ xem Booking Deposits của mình',
            'contract.booking_deposit.create' => 'Tạo Booking Deposit',
            'contract.booking_deposit.update' => 'Cập nhật Booking Deposit',
            'contract.booking_deposit.delete' => 'Xóa Booking Deposit',
            'contract.booking_deposit.approve' => 'Duyệt Booking Deposit',
            'contract.booking_deposit.cancel' => 'Hủy Booking Deposit',
            'contract.booking_deposit.refund' => 'Hoàn tiền Booking Deposit',
            'contract.booking_deposit.mark_paid' => 'Đánh dấu đã thanh toán Booking Deposit',
            'contract.booking_deposit.create_invoice' => 'Tạo hóa đơn từ Booking Deposit',
            'contract.booking_deposit.create_lease' => 'Tạo hợp đồng từ Booking Deposit',
            'contract.booking_deposit.settings' => 'Quản lý cài đặt Booking Deposit',
        ],
    ],

    // AR/Billing Module: InvoiceRun, Invoice, InvoiceItem, Payment, Dunning
    'billing' => [
        'name' => 'AR & Billing Management',
        'description' => 'Quản lý InvoiceRun, Invoice, InvoiceItem, Payment, Dunning',
        'capabilities' => [
            'billing.access' => 'Truy cập module Billing',
            'billing.invoice.view' => 'Xem Invoice',
            'billing.invoice.view_all' => 'Xem tất cả Invoices',
            'billing.invoice.view_own' => 'Chỉ xem Invoices của mình',
            'billing.invoice.create' => 'Tạo Invoice',
            'billing.invoice.update' => 'Cập nhật Invoice',
            'billing.invoice.delete' => 'Xóa Invoice',
            'billing.invoice.issue' => 'Phát hành Invoice',
            'billing.invoice.run' => 'Chạy InvoiceRun',
            'billing.payment.view' => 'Xem Payment',
            'billing.payment.view_all' => 'Xem tất cả Payments',
            'billing.payment.view_own' => 'Chỉ xem Payments của mình',
            'billing.payment.create' => 'Tạo Payment',
            'billing.payment.update' => 'Cập nhật Payment',
            'billing.payment.delete' => 'Xóa Payment',
            'billing.dunning.view' => 'Xem Dunning',
            'billing.dunning.manage' => 'Quản lý Dunning',
            'billing.sepay.view' => 'Xem Sepay Transactions',
            'billing.sepay.manage' => 'Quản lý Sepay Transactions',
            'billing.sepay.settings' => 'Cài đặt Sepay',
            'billing.sepay.retry' => 'Thử lại Sepay Transaction',
            'billing.sepay.export' => 'Xuất Sepay Transactions',
            'billing.webhook_log.view' => 'Xem Webhook Logs',
            'billing.webhook_log.manage' => 'Quản lý Webhook Logs',
            'billing.webhook_log.retry' => 'Thử lại Webhook Log',
            'billing.payment_cycle.view' => 'Xem Payment Cycle Settings',
            'billing.payment_cycle.manage' => 'Quản lý Payment Cycle Settings',
            'billing.services.view' => 'Xem Services',
            'billing.services.create' => 'Tạo Service',
            'billing.services.update' => 'Cập nhật Service',
            'billing.services.delete' => 'Xóa Service',
            'billing.lease_service.view' => 'Xem Lease Service Settings',
            'billing.lease_service.manage' => 'Quản lý Lease Service Settings',
        ],
    ],

    // Work Management Module: Ticket, TicketLog, SLA
    'work' => [
        'name' => 'Work Management',
        'description' => 'Quản lý Ticket, TicketLog, SLA',
        'capabilities' => [
            'work.access' => 'Truy cập module Work Management',
            'work.ticket.view' => 'Xem Ticket',
            'work.ticket.view_all' => 'Xem tất cả Tickets',
            'work.ticket.view_own' => 'Chỉ xem Tickets của mình',
            'work.ticket.create' => 'Tạo Ticket',
            'work.ticket.update' => 'Cập nhật Ticket',
            'work.ticket.delete' => 'Xóa Ticket',
            'work.ticket.assign' => 'Gán Ticket',
            'work.ticket.resolve' => 'Giải quyết Ticket',
            'work.log.view' => 'Xem TicketLog',
            'work.log.create' => 'Tạo TicketLog',
            'work.sla.view' => 'Xem SLA',
            'work.sla.manage' => 'Quản lý SLA',
            'work.activity_type.view' => 'Xem Activity Type',
            'work.activity_type.create' => 'Tạo Activity Type',
            'work.activity_type.update' => 'Cập nhật Activity Type',
            'work.activity_type.delete' => 'Xóa Activity Type',
            'work.activity_source.view' => 'Xem Activity Source',
            'work.activity_source.create' => 'Tạo Activity Source',
            'work.activity_source.update' => 'Cập nhật Activity Source',
            'work.activity_source.delete' => 'Xóa Activity Source',
        ],
    ],

    // Finance Module: Cashflow, Commission, Payroll
    'finance' => [
        'name' => 'Finance Management',
        'description' => 'Quản lý Cashflow, Commission, Payroll và các tài chính',
        'capabilities' => [
            'finance.access' => 'Truy cập module Finance',
            'finance.cashflow.view' => 'Xem Cashflow',
            'finance.cashflow.create' => 'Tạo Cashflow',
            'finance.cashflow.update' => 'Cập nhật Cashflow',
            'finance.cashflow.delete' => 'Xóa Cashflow',
            'finance.commission.view' => 'Xem Commission Events',
            'finance.commission.create' => 'Tạo Commission Events',
            'finance.commission.update' => 'Cập nhật Commission Events',
            'finance.commission.delete' => 'Xóa Commission Events',
            'finance.commission.approve' => 'Duyệt Commission Events',
            'finance.commission.pay' => 'Thanh toán Commission Events',
            'finance.payroll.view' => 'Xem Payroll Payslips',
            'finance.payroll.create' => 'Tạo Payroll Payslips',
            'finance.payroll.update' => 'Cập nhật Payroll Payslips',
            'finance.payroll.delete' => 'Xóa Payroll Payslips',
            'finance.payroll.approve' => 'Duyệt Payroll Payslips',
            'finance.payroll.pay' => 'Thanh toán Payroll Payslips',
            'finance.salary_advance.view' => 'Xem Salary Advances',
            'finance.salary_advance.create' => 'Tạo Salary Advances',
            'finance.salary_advance.update' => 'Cập nhật Salary Advances',
            'finance.salary_advance.delete' => 'Xóa Salary Advances',
            'finance.salary_advance.approve' => 'Duyệt Salary Advances',
            'finance.salary_advance.reject' => 'Từ chối Salary Advances',
            'finance.vendor.view' => 'Xem Vendor',
            'finance.vendor.create' => 'Tạo Vendor',
            'finance.vendor.update' => 'Cập nhật Vendor',
            'finance.vendor.delete' => 'Xóa Vendor',
            'finance.company_invoice.view' => 'Xem Company Invoice',
            'finance.company_invoice.create' => 'Tạo Company Invoice',
            'finance.company_invoice.update' => 'Cập nhật Company Invoice',
            'finance.company_invoice.delete' => 'Xóa Company Invoice',
            'finance.company_invoice.approve' => 'Duyệt Company Invoice',
            'finance.company_invoice.pay' => 'Thanh toán Company Invoice',
            'finance.cash_outflow.view' => 'Xem Cash Outflow',
            'finance.cash_outflow.create' => 'Tạo Cash Outflow',
            'finance.cash_outflow.update' => 'Cập nhật Cash Outflow',
            'finance.cash_outflow.delete' => 'Xóa Cash Outflow',
            'finance.commission_policy.view' => 'Xem Commission Policy',
            'finance.commission_policy.create' => 'Tạo Commission Policy',
            'finance.commission_policy.update' => 'Cập nhật Commission Policy',
            'finance.commission_policy.delete' => 'Xóa Commission Policy',
            'finance.payroll_cycle.view' => 'Xem Payroll Cycle',
            'finance.payroll_cycle.create' => 'Tạo Payroll Cycle',
            'finance.payroll_cycle.update' => 'Cập nhật Payroll Cycle',
            'finance.payroll_cycle.delete' => 'Xóa Payroll Cycle',
            'finance.payroll_cycle.lock' => 'Khóa Payroll Cycle',
            'finance.payroll_cycle.generate' => 'Tạo Payroll Payslips từ Cycle',
            'finance.financial_management.view' => 'Xem Financial Management',
            'finance.financial_management.manage' => 'Quản lý Financial Management',
            'finance.financial_management.send_reminder' => 'Gửi nhắc nhở thanh toán',
            'finance.report.view' => 'Xem Finance Reports',
            'finance.report.export' => 'Xuất Finance Reports',
        ],
    ],

    // Settings Module: System Settings, Organization Banking, Organization Email
    'settings' => [
        'name' => 'System Settings',
        'description' => 'Quản lý cài đặt hệ thống, ngân hàng tổ chức, email tổ chức',
        'capabilities' => [
            'settings.access' => 'Truy cập module Settings',
            'settings.system.view' => 'Xem System Settings',
            'settings.system.manage' => 'Quản lý System Settings',
            'settings.organization_banking.view' => 'Xem Organization Banking',
            'settings.organization_banking.create' => 'Tạo Organization Banking',
            'settings.organization_banking.update' => 'Cập nhật Organization Banking',
            'settings.organization_banking.delete' => 'Xóa Organization Banking',
            'settings.organization_email.view' => 'Xem Organization Email Settings',
            'settings.organization_email.update' => 'Cập nhật Organization Email Settings',
            'settings.organization_email.test' => 'Test Organization Email Connection',
        ],
    ],

    // Subscription Module: Subscription Management
    'subscription' => [
        'name' => 'Subscription Management',
        'description' => 'Quản lý đăng ký và thanh toán gói dịch vụ',
        'capabilities' => [
            'subscription.access' => 'Truy cập module Subscription',
            'subscription.view' => 'Xem Subscriptions',
            'subscription.register' => 'Đăng ký Subscription',
            'subscription.payment' => 'Thanh toán Subscription',
            'subscription.invoice.view' => 'Xem Subscription Invoices',
        ],
    ],
];

